spring.application.name=velocrm
spring.datasource.url=jdbc:h2:mem:velocrmdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Disable docker compose autoconfiguration to use H2 in tests
spring.docker.compose.enabled=false
