spring.application.name=velocrm
spring.threads.virtual.enabled=true
spring.datasource.url=jdbc:h2:mem:velocrmdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Disable docker compose autoconfiguration to use H2 in tests/dev by default
spring.docker.compose.enabled=false

---
# Docker profile settings
spring.config.activate.on-profile=docker
spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

---
# Supabase profile settings
spring.config.activate.on-profile=supabase
spring.datasource.url=${SUPABASE__URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

